name: deploy to TEST
on: 
 pull_request:
    branches:
      - develop

jobs:
  build: 
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [14.15.3]
    steps:
      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: setup python3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: install pytest
        run: | 
          python -m pip install --upgrade pip
          pip install pytest
      - name: Unit test 
        run: |
          pytest src/main.py

